import { defineConfig } from 'oxlint'

export default defineConfig({
  categories: {
    correctness: 'error',
    suspicious: 'error',
  },
  env: {
    browser: true,
    es2022: true,
    node: true,
  },
  jsPlugins: ['@e18e/eslint-plugin'],
  overrides: [
    {
      files: ['app/sw.ts'],
      rules: {
        'no-restricted-globals': ['error', { message: 'Use `globalThis` instead.', name: 'global' }],
      },
    },
  ],
  plugins: ['typescript', 'unicorn', 'oxc', 'import', 'vue'],
  rules: {
    'accessor-pairs': [
      'error',
      {
        enforceForClassMembers: true,
        enforceForTSTypes: false,
        getWithoutSet: false,
        setWithoutGet: true,
      },
    ],
    'array-callback-return': ['error', { allowImplicit: false, allowVoid: false, checkForEach: false }],
    'e18e/ban-dependencies': 'error',
    'e18e/prefer-array-at': 'error',
    'e18e/prefer-array-fill': 'error',
    'e18e/prefer-array-from-map': 'error',
    'e18e/prefer-array-some': 'error',
    'e18e/prefer-array-to-reversed': 'error',
    'e18e/prefer-array-to-sorted': 'error',
    'e18e/prefer-array-to-spliced': 'error',
    'e18e/prefer-date-now': 'error',
    'e18e/prefer-includes': 'error',
    'e18e/prefer-nullish-coalescing': 'error',
    'e18e/prefer-object-has-own': 'error',
    'e18e/prefer-regex-test': 'error',
    'e18e/prefer-spread-syntax': 'error',
    'e18e/prefer-static-regex': 'error',
    'e18e/prefer-string-fromcharcode': 'error',
    'e18e/prefer-timer-args': 'error',
    'e18e/prefer-url-canparse': 'error',
    eqeqeq: ['error', 'smart'],
    'eslint/sort-keys': 'warn',
    'import/consistent-type-specifier-style': ['error', 'prefer-top-level'],
    'import/first': 'error',
    'import/no-duplicates': 'off',
    'import/no-mutable-exports': 'error',
    'import/no-named-default': 'error',
    'new-cap': ['error', { capIsNew: false, newIsCap: true, properties: true }],
    'no-alert': 'error',
    'no-console': ['error', { allow: ['warn', 'error'] }],
    'no-empty': ['error', { allowEmptyCatch: true }],
    'no-empty-pattern': ['error', { allowObjectPatternsAsParameters: false }],
    'no-proto': 'error',
    'no-regex-spaces': 'error',
    'no-restricted-globals': [
      'error',
      { message: 'Use `globalThis` instead.', name: 'global' },
      { message: 'Use `globalThis` instead.', name: 'self' },
    ],
    'no-restricted-properties': [
      'error',
      { message: 'Use `Object.getPrototypeOf` or `Object.setPrototypeOf` instead.', property: '__proto__' },
      { message: 'Use `Object.defineProperty` instead.', property: '__defineGetter__' },
      { message: 'Use `Object.defineProperty` instead.', property: '__defineSetter__' },
      { message: 'Use `Object.getOwnPropertyDescriptor` instead.', property: '__lookupGetter__' },
      { message: 'Use `Object.getOwnPropertyDescriptor` instead.', property: '__lookupSetter__' },
    ],
    'no-sequences': ['error', { allowInParentheses: true }],
    'no-shadow': 'off',
    'no-underscore-dangle': 'off',
    'no-unused-expressions': [
      'error',
      {
        allowShortCircuit: true,
        allowTaggedTemplates: true,
        allowTernary: true,
      },
    ],
    'no-useless-call': 'warn',
    'no-useless-computed-key': ['error', { enforceForClassMembers: true }],
    'no-useless-rename': 'error',
    'no-useless-return': 'error',
    'no-var': 'error',
    'object-shorthand': ['error', 'always', { avoidQuotes: true, ignoreConstructors: false }],
    'prefer-const': ['error', { destructuring: 'all', ignoreReadBeforeAssign: true }],
    'prefer-exponentiation-operator': 'error',
    'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    'preserve-caught-error': 'off',
    'typescript/consistent-type-definitions': ['error', 'interface'],
    'typescript/consistent-type-imports': [
      'error',
      {
        disallowTypeAnnotations: false,
        fixStyle: 'separate-type-imports',
        prefer: 'type-imports',
      },
    ],
    'unicode-bom': ['error', 'never'],
    'unicorn/consistent-function-scoping': 'off',
    'unicorn/require-post-message-target-origin': 'off',
    'vars-on-top': 'error',
    yoda: ['error', 'never'],
  },
})
